ROUTES = {
    'sanity': '/',
    'login': '/login',
    'logout': '/logout',
    'users': '/users',
    'current_user': '/current-user',
    'teaching': '/current-user/teaching',
    'refresh': '/refresh',
    'resources': '/resources/<subject_id>/pdf',
    'resources-keywords': '/resources/<subject_id>/keywords',
    'articles': '/articles/pdf',
    'articles-keywords': '/articles/keywords',
    'discussion-groups': '/discussion-groups',
    'create-group': '/create-group',
    'groups': '/groups/<group_id>',
    'announcements': '/announcements/<discussion_group_id>',
    'profile': '/profile/<teacher_id>',
    'students': '/students',
    'teachers': '/teachers'
}
